.\"                                      Hey, EMACS: -*- nroff -*-
.TH WahaCC "1" "February 2014" "Waha Control Center" "User Commands"
.SH NAME
wahacc \- Open Control Center
.SH DESCRIPTION
This manual page documents briefly the
.B wahacc
commands.
.PP
\fBwahacc\fP is a simple control center 
has the basic tools to configure a Debian based distributions.
.SH AUTHOR
Written by Abdelkarim Guettaf <gkraim@gmail.com>
.SH "REPORTING BUGS"
Report ls bugs to <wahaproject@gmail.com>
.br
WCC home page: <http://www.wahaproject.org/>
.br
.SH COPYRIGHT
Copyright: 1434 WahaProject.Org
.br
License: Waqf Public License
.br
the complete text of the Waqf Public License
.br
can be found at `http://ojuba.org/wiki/waqf/license'
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law
