#!/bin/bash
echo Starting...
if [ $(grep -r '^APT::Periodic::Unattended-Upgrade' /etc/apt/apt.conf.d/* | wc -l) = "0" ]; then
	echo "APT::Periodic::Unattended-Upgrade \"1\";" >> /etc/apt/apt.conf.d/20auto-upgrades
fi

if [ $1 = "enable" ]; then
	sed -i 's/APT::Periodic::Unattended-Upgrade "0";/APT::Periodic::Unattended-Upgrade "1";/g' /etc/apt/apt.conf.d/*
else
	sed -i 's/APT::Periodic::Unattended-Upgrade "1";/APT::Periodic::Unattended-Upgrade "0";/g' /etc/apt/apt.conf.d/*
fi
echo Done.
read -p "Press [Enter] key to exit..."
